### ISSUE TITLE
Grey Screen on Start

### ISSUE THREAD

**Issue by dotsam** [robertventurini/FlyingToasters#1]
Hello! Thanks for making this version of the flying toaster screensaver, as it's the only one I've found that I can compile for Apple Silicon and thus not be burning CPU cycles running a screensaver (a new Universal build would probably help others who can't/won't build from source)

The issue I'm reporting is a ~1 second long grey screen that appears when the screensaver starts. I'm not sure if this is M1/Big Sur specific, but from some quick Googling, this seems to be related to SceneKit and the setting up of the scene and the view.

I tried a few copy/paste StackOverflow fixes related to setting a background colour differently/earlier, but with no chance. Do you see this issue on an Intel Mac, and do you have any thoughts on how to fix it?

**Comment by robertventurini** [comment]
Hey Sam! I think I've corrected your issue, not sure how I missed that because it was pretty glaring on my 2018 machine I tried here. Originally I wrote this on a Mid-2010 MBP running OS X 10.9 and its possible that SpriteKit behaved differently on older versions of macOS. Whatever the case, the problem _should_ be corrected and I've uploaded a new FAT binary that should give you native support on your Apple Silicon machine. Unfortunately I am unable to test Apple Silicon support, my newest device is still intel based. If you could let me know if it doesn't run natively for you that'd be great!

Thanks,
Robert

**Comment by dotsam** [comment]
Thanks Robert, this fixes the problem for me, and the new binary works on an M1 just fine. Thanks!
